spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: dog
    password: services
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: never
springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
server:
  servlet:
    context-path: /dog
logging:
  level:
    org.hibernate.SQL: DEBUG